import { sql } from 'drizzle-orm';
import { jsonb, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Column helpers shared by every table.
 *
 * Conventions this file encodes, and the reasoning behind each:
 *
 *  - **UUID primary keys.** Ids are generated by the database but are safe to
 *    mint client-side too, which matters for offline forms and for the event
 *    bus, where a producer needs an id before the row exists.
 *  - **TIMESTAMPTZ everywhere.** The platform is multi-tenant across time
 *    zones; a naive timestamp is a bug waiting for a client in another region.
 *  - **`workspace_id` on every tenant-scoped table**, even when it is
 *    derivable through a parent. It is what row-level security keys on, and it
 *    keeps the tenant predicate on a single index instead of a join.
 *  - **Money as integer minor units.** Never a float, never `numeric` read
 *    into a JS number.
 */

export const primaryKeyColumn = () => uuid('id').primaryKey().defaultRandom();

export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

/**
 * Soft deletion, used only where history has real value (contacts, content,
 * leads). Everything else deletes for real — a `deleted_at` column on a table
 * nobody ever restores from is just a permanent source of forgotten
 * `WHERE deleted_at IS NULL` bugs.
 */
export const softDelete = {
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
};

export const metadata = () =>
  jsonb('metadata')
    .notNull()
    .default(sql`'{}'::jsonb`);

export const emptyJsonObject = sql`'{}'::jsonb`;
export const emptyJsonArray = sql`'[]'::jsonb`;
