import type { Metadata, Viewport } from 'next';
import { headers } from 'next/headers';
import type { ReactNode } from 'react';
import { getWorkspace } from '@/lib/workspace';
import { buildTokenCss } from '@/lib/tokens';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { AttributionCapture } from '@/components/attribution-capture';
import './globals.css';

export async function generateMetadata(): Promise<Metadata> {
  const workspace = await getWorkspace();
  return {
    // Every page's own title fills the %s. Set here so the brand suffix is
    // defined once rather than concatenated at each call site.
    title: { default: workspace.brand.name, template: `%s | ${workspace.brand.name}` },
    metadataBase: new URL(workspace.siteUrl),
    ...(workspace.brand.tagline ? { description: workspace.brand.tagline } : {}),
    ...(workspace.brand.logoUrl ? { icons: { icon: workspace.brand.logoUrl } } : {}),
  };
}

/**
 * `viewport-fit` and a real `themeColor` rather than the defaults.
 *
 * Separate from `metadata` because Next requires it: a viewport in the
 * metadata export is ignored, silently.
 */
export async function generateViewport(): Promise<Viewport> {
  const workspace = await getWorkspace();
  return {
    width: 'device-width',
    initialScale: 1,
    themeColor: workspace.brand.primaryColor ?? '#1a56db',
  };
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const workspace = await getWorkspace();

  // Set by middleware.ts, which is also what put it in the CSP. Reading it
  // here is what lets the token stylesheet be inline without `unsafe-inline`.
  const nonce = (await headers()).get('x-nonce') ?? undefined;

  return (
    <html lang={workspace.locale.defaultLocale}>
      <head>
        {/*
          Design tokens, generated from the tenant's brand configuration and
          inlined so they are in the first paint rather than one round trip
          later. Roughly a kilobyte — smaller than the request that would fetch
          it.
        */}
        {/*
          eslint-disable no-restricted-syntax -- generated by `buildTokenCss`
          from validated config: hex colours matched against a regex, plus
          fixed numeric scales. No user input reaches this string.
        */}
        <style
          {...(nonce ? { nonce } : {})}
          dangerouslySetInnerHTML={{ __html: buildTokenCss(workspace) }}
        />
        {/* eslint-enable no-restricted-syntax */}
      </head>
      <body>
        <a href="#main" className="skip-link">
          Skip to content
        </a>

        <SiteHeader workspace={workspace} />

        <main id="main">{children}</main>

        <SiteFooter workspace={workspace} />

        <AttributionCapture />
      </body>
    </html>
  );
}
